const path = require('path');
const fs = require('fs');

function generateEnvModule() {
  const envPath = path.resolve(__dirname, '.env.local');
  const fallbackPath = path.resolve(__dirname, '.env');
  const filePath = fs.existsSync(envPath) ? envPath : fallbackPath;

  console.log('[env-gen] Reading from:', filePath);
  console.log('[env-gen] File exists:', fs.existsSync(filePath));

  const vars = {};
  if (fs.existsSync(filePath)) {
    const raw = fs.readFileSync(filePath, 'utf8');
    console.log('[env-gen] Raw file contents:', raw);
    const lines = raw.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const value = trimmed.slice(eqIdx + 1).trim();
      if (key.startsWith('EXPO_PUBLIC_')) {
        vars[key] = value;
      }
    }
  }

  console.log('[env-gen] Parsed vars:', vars);

  const outPath = path.resolve(__dirname, 'lib/env.generated.ts');
  const content =
    '// AUTO-GENERATED by metro.config.js\n' +
    Object.entries(vars)
      .map(([k, v]) => `export const ${k} = ${JSON.stringify(v)};`)
      .join('\n') +
    '\n';

  fs.writeFileSync(outPath, content, 'utf8');
  console.log('[env-gen] Wrote', Object.keys(vars).length, 'variables to', outPath);
}

generateEnvModule();

const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname);

module.exports = withNativeWind(config, { input: './global.css' });